--- # Poggit-CI Manifest. Open the CI at https://poggit.pmmp.io/ci/Shock95x/AuctionHouse
projects:
  AuctionHouse:
    path: ""
    icon: icon.png
    libs:
    - src: poggit/libasynql/libasynql
      version: ^3.3.1
    - src: muqsit/InvMenu/InvMenu
      branch: master
      version: ^4.1.1
    - src: SOF3/await-generator/await-generator
      version: ^3.1.0
    - src: ifera-mc/UpdateNotifier/UpdateNotifier
      version: ^2.1.0
    - src: CortexPE/Commando/Commando
      version: ^2.1.1
...
